---
title: "Proyecto2"
---

# Hacer modelos con sus datos

La idea de proyecto 2 es hacer un modelo adecuado con sus datos. Es integral tener datos en las formas correctas (integral, número, factor, etc..). Además, debería probar las supuestos del tipo de modelo elegido (si eliges un tipo non-paramétrico, debería probar por normalidad y covarianza todavía).

Debería entregar un pdf de R Markdown (con cajas de códigos incluidos) con:

-   Un corrgram o PCA con las variables explicativas y una oración explicando lo que significa el corrgram/PCA

-   Un anova o kruskal-wallis (paramétrico o non-paramétrico) con prueba de normalidad, outliers y homogeneidad de la varianza y una oración explicando sus resultados

-   Un par de modelos (paramétrico o non-paramétrico) con pruebas de las supuestos (y explica los resultados de estas pruebas)

-   Un modelo final elegido de las opciones con un método adecuado y un párrafo explicando como lo elegiste lo mejor e interpretando los resultados

# Rúbrica

|                                           | 1                                             | 3                                                                         | 5                                                                | 7                                                                              |
|-------------------------------------------|-----------------------------------------------|---------------------------------------------------------------------------|------------------------------------------------------------------|--------------------------------------------------------------------------------|
| Corrgram o PCA                            | Falta corrgram/pca                            | Sin todo los variables de interés (por el                                 |                                                                  |                                                                                |
| modelo) o sin interpretación              | Con todo los variables, pero mal interpretado | Incluye todo los variables de interés, con                                |                                                                  |                                                                                |
| interpretación adecuado, bien organizado  |                                               |                                                                           |                                                                  |                                                                                |
| Anova o kruskal-wallis                    | Falta anova/kruskal wallis                    | Elección de la prueba incorrecta desde sus                                |                                                                  |                                                                                |
| pruebas o falta algun supuesto            | Los supuestos y prueba correcto, pero mal     |                                                                           |                                                                  |                                                                                |
| interpretado                              | Todo corecto, o con errores chicos            |                                                                           |                                                                  |                                                                                |
| Pruebas de los supuestos (de los modelos) | Falta pruebas de los supuestos                | Hay la mayoría de los supuestos con errores en interpretación             | Todos los supuestos incluidos y explicados con pocos errores     | Buen interpretación de los supuestos                                           |
| Grupos de modelos                         | Falta un par de modelos (o sea solo hay uno)  | Modelos con familia mal elegido o tipo incorrecto, y/o sin interpretación | Modelos buen diseñados, con buena familia, pero mal interpretado | Todo corecto, o con errores chicos                                             |
| Elección del modelo final                 | Sin modelo final                              | Modelo final elegido pero no interpretado o mal elegido                   | Modelo final bien elegido, y con pocas errores en interpretación | Modelo bien diseñado, elegido y interpretado: es claro como elegiste su modelo |
| Organización del R Markdown               | Sin organización, sin texto normal, sin pdf   | Mal exportado, sin párrafos o títulos                                     | Bien hecho, pero sin un elemento                                 | Con párrafos, fotos, títulos, exportada como pdf                               |
